.TH .AUTO_SIZE_INTERNAL 1 2025-Sep "internal" "Internal canvas dimension calculator"
.SH NAME
.auto_size_internal \- .auto_size_internal(dims, padding,
    <i>scale</i> = <span style='color: green;'>1</span>)
.SH SYNOPSIS
\fI.auto_size_internal(dims, padding,
    <i>scale</i> = <span style='color: green;'>1</span>)\fR
.SH DESCRIPTION
.PP
Helper function that computes base canvas dimensions with padding and scaling.
.PP
.SH OPTIONS
.PP
\fBdims\fB \fR\- . Original image dimensions (numeric vector [width, height])
.PP
.PP
\fBpadding\fB \fR\- . Numeric vector specifying padding [top, right, bottom, left]
.PP
.PP
\fBscale\fB \fR\- 1. Numeric scaling factor for initial dimension adjustment
.PP
.SH VALUE
.PP
Numeric vector [width, height] representing:
(original dimensions * scale) + padding adjustments
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..auto_size_internal at utils.R:line 44
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
