.TH .AUTO_SIZE_INTERNAL 1 2023-Dec "" "Evaluate the canvas size"
.SH NAME
.auto_size_internal \- .auto_size_internal(dims, padding,
    <i>scale</i> = <span style='color: green;'>1</span>)
.SH SYNOPSIS
\fI.auto_size_internal(dims, padding,
    <i>scale</i> = <span style='color: green;'>1</span>)\fR
.SH OPTIONS
.PP
\fBdims\fB \fR\- . 
.PP
.PP
\fBpadding\fB \fR\- . 
.PP
.PP
\fBscale\fB \fR\- 1. 
.PP
.SH VALUE
.PP
A size numeric vector with two elements: w,h
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..auto_size_internal at layout.R:line 85
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
