.TH .AUTO_SIZE_INTERNAL 1 2022-11-28 "" ".auto_size_internal"
.SH NAME
.auto_size_internal \- .auto_size_internal(dims, padding,
    <i>scale</i> = 1)
.SH SYNOPSIS
\fI.auto_size_internal(dims, padding,
    <i>scale</i> = 1)\fR
.SH OPTIONS
.PP
\fBdims\fB \fR\- . 
.PP
.PP
\fBpadding\fB \fR\- . 
.PP
.PP
\fBscale\fB \fR\- 1. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..auto_size_internal at layout.R:line 29
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
