.TH AUTOSIZE 1 2022-04-28 "" "evaluate of the canvas size and padding"
.SH NAME
autoSize \- autoSize(dims, padding, scale = 1)
.SH SYNOPSIS
\fIautoSize(dims, padding, scale = 1)\fR
.SH OPTIONS
.PP
\fBdims\fB \fR\- . the dimension data of the MSImaging raw data. it should be a numeric vector with at least two element standards for ``[w, h]``; or a list object with at least two slot elements which are named ``w`` and ``h``.
.PP
.PP
\fBpadding\fB \fR\- . the padding element is a numeric vector with four elements standards for css padding value: ``[top, right, bottom, left]``.
.PP
.PP
\fBscale\fB \fR\- 1. a numeric factor for describ the pixel scale size in MSImaging rendering process. default value is 1 means no scale, just rendering of the origina size!
.PP
.SH VALUE
.PP
this function returns a list object that contains the recommended size value for the MSImaging plot. the result value contains two slot elements: size element is a dimension vector with two elements standards for ``[w, h]``.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.autoSize at layout.R:line 22
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
