.TH CUSTOM_INTENSITY_FILTER 1 2024-Jul "" "custom_intensity_filter"
.SH NAME
custom_intensity_filter \- custom_intensity_filter(ion, filters,
    <i>MSI.TrIQ</i> = <span style='color: green;'>0.8</span>)
.SH SYNOPSIS
\fIcustom_intensity_filter(ion, filters,
    <i>MSI.TrIQ</i> = <span style='color: green;'>0.8</span>)\fR
.SH OPTIONS
.PP
\fBion\fB \fR\- . 
.PP
.PP
\fBfilters\fB \fR\- . 
.PP
.PP
\fBMSI.TrIQ\fB \fR\- 0.8. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.custom_intensity_filter at MSIMatrixHeatmapGroupPlot.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
