.TH GEOM_BLUE 1 2021-10-28 "" "Do MSI rendering for mz as blue layer"
.SH NAME
geom_blue \- geom_blue(mz, tolerance = da:0.3)
.SH SYNOPSIS
\fIgeom_blue(mz, tolerance = da:0.3)\fR
.SH OPTIONS
.PP
\fBmz\fB \fR\- . the m/z value of the target ion
.PP
.PP
\fBtolerance\fB \fR\- da:0.3. 
.PP
.SH VALUE
.PP
a ggplot layer object for do MS-imaging rendering.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.geom_blue at MSImaging.R:line 27
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
