.TH GEOM_GREEN 1 2025-Nov "" "Create green channel MS imaging layer"
.SH NAME
geom_green \- geom_green(mz,
    <i>tolerance</i> = 'getOption'('mzdiff', 'default' = 'da:0.3'))
.SH SYNOPSIS
\fIgeom_green(mz,
    <i>tolerance</i> = 'getOption'('mzdiff', 'default' = 'da:0.3'))\fR
.SH DESCRIPTION
.PP
Generates a ggplot2 layer for mass spectrometry imaging (MSI) data visualization
in green color channel corresponding to specified m/z value.
.PP
.SH OPTIONS
.PP
\fBmz\fB \fR\- . numeric. The target mass-to-charge ratio (m/z) value for ion detection.
.PP
.PP
\fBtolerance\fB \fR\- 'getOption'('mzdiff', 'default' = 'da:0.3'). character or numeric. Mass accuracy tolerance. See geom_red() for format details.
.PP
.SH VALUE
.PP
A ggplot2 layer object displaying ion distribution in green color scale.
.PP
.SH EXAMPLES
.PP
#\dontrun{

plot_base() + geom_green(556.276)

#}
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.geom_green at MSImaging.R:line 36
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
