.TH GEOM_GREEN 1 2021-10-14 "" "Do MSI rendering for mz as green layer"
.SH NAME
geom_green \- geom_green(mz)
.SH SYNOPSIS
\fIgeom_green(mz)\fR
.SH OPTIONS
.PP
\fBmz\fB \fR\- 
.PP
.SH VALUE
.PP
a ggplot layer object for do MS-imaging rendering.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.geom_green at MSImaging.R:line 17
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
