.TH GEOM_BLANKET 1 2022-09-20 "" "geom_blanket"
.SH NAME
geom_blanket \- geom_blanket(mz,
    <i>tolerance</i> = getOption(mzdiff, default = da:0.3))
.SH SYNOPSIS
\fIgeom_blanket(mz,
    <i>tolerance</i> = getOption(mzdiff, default = da:0.3))\fR
.SH OPTIONS
.PP
\fBmz\fB \fR\- . 
.PP
.PP
\fBtolerance\fB \fR\- getOption(mzdiff, default = da:0.3). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.geom_blanket at MSImaging.R:line 31
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
