.TH GEOM_RED 1 2024-Apr "" "Do MSI rendering for mz as red layer"
.SH NAME
geom_red \- geom_red(mz,
    <i>tolerance</i> = getOption(mzdiff, default = da:0.3))
.SH SYNOPSIS
\fIgeom_red(mz,
    <i>tolerance</i> = getOption(mzdiff, default = da:0.3))\fR
.SH OPTIONS
.PP
\fBmz\fB \fR\- . the m/z value of the target ion
.PP
.PP
\fBtolerance\fB \fR\- getOption(mzdiff, default = da:0.3). 
.PP
.SH VALUE
.PP
a ggplot layer object for do MS-imaging rendering.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.geom_red at MSImaging.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
