.TH GEOM_GREEN 1 2022-10-17 "" "Do MSI rendering for mz as green layer"
.SH NAME
geom_green \- geom_green(mz,
    <i>tolerance</i> = getOption(mzdiff, default = da:0.3))
.SH SYNOPSIS
\fIgeom_green(mz,
    <i>tolerance</i> = getOption(mzdiff, default = da:0.3))\fR
.SH OPTIONS
.PP
\fBmz\fB \fR\- . the m/z value of the target ion
.PP
.PP
\fBtolerance\fB \fR\- getOption(mzdiff, default = da:0.3). 
.PP
.SH VALUE
.PP
a ggplot layer object for do MS-imaging rendering.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.geom_green at MSImaging.R:line 17
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
