.TH GEOM_BLUE 1 2026-Jan "" "Create blue channel MS imaging layer"
.SH NAME
geom_blue \- geom_blue(mz,
    <i>tolerance</i> = 'getOption'('mzdiff', 'default' = 'da:0.3'))
.SH SYNOPSIS
\fIgeom_blue(mz,
    <i>tolerance</i> = 'getOption'('mzdiff', 'default' = 'da:0.3'))\fR
.SH DESCRIPTION
.PP
Generates a ggplot2 layer for mass spectrometry imaging (MSI) data visualization
in blue color channel corresponding to specified m/z value.
.PP
.SH OPTIONS
.PP
\fBmz\fB \fR\- . numeric. The target mass-to-charge ratio (m/z) value for ion detection.
.PP
.PP
\fBtolerance\fB \fR\- 'getOption'('mzdiff', 'default' = 'da:0.3'). character or numeric. Mass accuracy tolerance. See geom_red() for format details.
.PP
.SH VALUE
.PP
A ggplot2 layer object displaying ion distribution in blue color scale.
.PP
.SH EXAMPLES
.PP
#\dontrun{

plot_base() + geom_blue(1024.673)

#}
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.geom_blue at MSImaging.R:line 54
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
