.TH MSI_IONSTATPLOT 1 2022-12-16 "" "Stat plot combine with the MS-imaging"
.SH NAME
MSI_ionStatPlot \- MSI_ionStatPlot(mzpack, mz, met, sampleinfo,
    <i>savePng</i> = ./Rplot.png,
    <i>ionName</i> = <span style='color: blue;'>NULL</span>,
    <i>size</i> = [2400, 1000],
    <i>colorMap</i> = <span style='color: blue;'>NULL</span>,
    <i>MSI.colorset</i> = viridis:turbo,
    <i>ggStatPlot</i> = <span style='color: blue;'>NULL</span>,
    <i>padding.top</i> = 150,
    <i>padding.right</i> = 200,
    <i>padding.bottom</i> = 150,
    <i>padding.left</i> = 150,
    <i>interval</i> = 50,
    <i>combine.layout</i> = [4, 5],
    <i>jitter.size</i> = 8,
    <i>TrIQ</i> = 0.65,
    <i>backcolor</i> = black)
.SH SYNOPSIS
\fIMSI_ionStatPlot(mzpack, mz, met, sampleinfo,
    <i>savePng</i> = ./Rplot.png,
    <i>ionName</i> = <span style='color: blue;'>NULL</span>,
    <i>size</i> = [2400, 1000],
    <i>colorMap</i> = <span style='color: blue;'>NULL</span>,
    <i>MSI.colorset</i> = viridis:turbo,
    <i>ggStatPlot</i> = <span style='color: blue;'>NULL</span>,
    <i>padding.top</i> = 150,
    <i>padding.right</i> = 200,
    <i>padding.bottom</i> = 150,
    <i>padding.left</i> = 150,
    <i>interval</i> = 50,
    <i>combine.layout</i> = [4, 5],
    <i>jitter.size</i> = 8,
    <i>TrIQ</i> = 0.65,
    <i>backcolor</i> = black)\fR
.SH OPTIONS
.PP
\fBmzpack\fB \fR\- . a mzpack data object used for do MS-imaging or other data object that contains the ms-imaging layer data and could be recognized by the ggplot ms-imaging function.
.PP
.PP
\fBmz\fB \fR\- . the target ion m/z value.
.PP
.PP
\fBmet\fB \fR\- . should be a list data object that contains the sample data, which this list the key names is the sample id set and the corresponding element value is the sample intensity value.
.PP
.PP
\fBsampleinfo\fB \fR\- . a data list set which could be used for defined the sample group information and the plot color value. this list data should be contains at least 3 required data fields: 1. group: the sample group name, used for display as the title label of each group data 2. id: a character vector that contains the necessary sample id reference to get the required sample data for each data group 3. color: a single character string value in html color format for specific the color of the bar/box/violin stat plot.
.PP
.PP
\fBsavePng\fB \fR\- ./Rplot.png. the filepath to save the image plot output.
.PP
.PP
\fBionName\fB \fR\- NULL. the display title string. the ion m/z value will be used if this parameter leaves default NULL.
.PP
.PP
\fBsize\fB \fR\- [2400, 1000]. 
.PP
.PP
\fBcolorMap\fB \fR\- NULL. a list object that contains the color set value that used for rendering the stat chartting, example as box/bar/violin. this list data object the key names should be the sample group tag and the corresponding value must be the sample intensity data value.
.PP
.PP
\fBMSI.colorset\fB \fR\- viridis:turbo. 
.PP
.PP
\fBggStatPlot\fB \fR\- NULL. default is bar plot.
.PP
.PP
\fBpadding.top\fB \fR\- 150. 
.PP
.PP
\fBpadding.right\fB \fR\- 200. 
.PP
.PP
\fBpadding.bottom\fB \fR\- 150. 
.PP
.PP
\fBpadding.left\fB \fR\- 150. 
.PP
.PP
\fBinterval\fB \fR\- 50. 
.PP
.PP
\fBcombine.layout\fB \fR\- [4, 5]. 
.PP
.PP
\fBjitter.size\fB \fR\- 8. 
.PP
.PP
\fBTrIQ\fB \fR\- 0.65. 
.PP
.PP
\fBbackcolor\fB \fR\- black. the background color of the MS-imaging plot
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.MSI_ionStatPlot at MSI_ionStatPlot.R:line 45
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
