.TH NPIXELS 1 2022-12-29 "" "count the scan ms1"
.SH NAME
npixels \- npixels(raw)
.SH SYNOPSIS
\fInpixels(raw)\fR
.SH OPTIONS
.PP
\fBraw\fB \fR\- . the mzpack object
.PP
.SH VALUE
.PP
the pixel counts(each pixel in the MS-imaging 2D plain is a ms1 scan in mzpack raw data).
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.npixels at mzpack.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
