.TH PLOTMSIMATRIXHEATMAP 1 2022-07-22 "" "Plot MS-Imaging heatmap matrix"
.SH NAME
PlotMSIMatrixHeatmap \- PlotMSIMatrixHeatmap(ions.data
layout = [3, 3],
colorSet = Jet,
MSI.TrIQ = 0.8,
gaussian = 3,
size = [2700, 2000],
canvasPadding = [50, 300, 50, 50],
cellPadding = [200, 100, 0, 100],
strict = TRUE)
.SH SYNOPSIS
\fIPlotMSIMatrixHeatmap(ions.data
layout = [3, 3],
colorSet = Jet,
MSI.TrIQ = 0.8,
gaussian = 3,
size = [2700, 2000],
canvasPadding = [50, 300, 50, 50],
cellPadding = [200, 100, 0, 100],
strict = TRUE)\fR
.SH OPTIONS
.PP
\fBions.data\fB \fR\- . 
.PP
.PP
\fBlayout\fB \fR\- [3, 3]. 
.PP
.PP
\fBcolorSet\fB \fR\- Jet. 
.PP
.PP
\fBMSI.TrIQ\fB \fR\- 0.8. 
.PP
.PP
\fBgaussian\fB \fR\- 3. 
.PP
.PP
\fBsize\fB \fR\- [2700, 2000]. 
.PP
.PP
\fBcanvasPadding\fB \fR\- [50, 300, 50, 50]. 
.PP
.PP
\fBcellPadding\fB \fR\- [200, 100, 0, 100]. 
.PP
.PP
\fBstrict\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.PlotMSIMatrixHeatmap at MSIMatrixHeatmapGroupPlot.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
