.\" man page create by R# package system.
.TH GGPLOT 1 2000-Jan "geom_MSIbackground" "geom_MSIbackground"
.SH NAME
geom_MSIbackground \- config of the background of the MS-imaging charting plot.
.SH SYNOPSIS
\fIgeom_MSIbackground(\fBbackground\fR as any);\fR
.SH DESCRIPTION
.PP
config of the background of the MS-imaging charting plot.
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- 
 the background color value or character vector \fBTIC\fR or \fBBPC\fR.
. 
.PP
.SH VALUE
.PP
this function returns clr object in types based on the **`background`** parameter:
 
 1. "TIC" or "BPC": @\fBT:ggplotMSImaging.layers.MSITICOverlap\fR
 2. html color code, or supported gdi image its file path: @\fBT:ggplotMSImaging.MSIBackgroundOption\fR
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
