.\" man page create by R# package system.
.TH GGPLOT 1 2000-Jan "geom_sample_outline" "geom_sample_outline"
.SH NAME
geom_sample_outline \- Create a plot layer of outline for the sample data
.SH SYNOPSIS
\fIgeom_sample_outline(\fBspots\fR as <generic> dataframe = \fB<NULL>\fR, 
\fBthreshold\fR as double = 0, 
\fBscale\fR as integer = 5, 
\fBdegree\fR as double = 20, 
\fBresolution\fR as integer = 1000, 
\fBq\fR as double = 0.1, 
\fBline_stroke\fR as any = "stroke: white; stroke-width: 6px; stroke-dash: solid;");\fR
.SH DESCRIPTION
.PP
Create a plot layer of outline for the sample data
.PP
.SH OPTIONS
.PP
\fBthreshold\fB \fR\- 
 the intensity threshold for make spatial spot binariation, for clean sample,
 leaves this parameter default zero, for sample with background, set this 
 parameter in range (0,1) for make spot cutoff.
. 
.PP
.PP
\fBscale\fB \fR\- contour tracing pixel rectangle scale size. 
.PP
.PP
\fBdegree\fB \fR\- -. 
.PP
.PP
\fBresolution\fB \fR\- -. 
.PP
.PP
\fBq\fB \fR\- -. 
.PP
.PP
\fBline_stroke\fB \fR\- a @\fBT:ggplot.elements.lineElement\fR that create via the ggplot function: \fBelement_line\fR.. 
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
