.\" man page create by R# package system.
.TH GGPLOT 1 2000-Jan "geom_MSIfilters" "geom_MSIfilters"
.SH NAME
geom_MSIfilters \- Options for apply the filter pieline on the imaging outputs
.SH SYNOPSIS
\fIgeom_MSIfilters(\fBfilters\fR as any = \fB<NULL>\fR, 
\fBfile\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Options for apply the filter pieline on the imaging outputs
.PP
.SH OPTIONS
.PP
\fBfilters\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- 
 this function also could read the filter pipeline file for construct the raster pipeline
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
