.\" man page create by R# package system.
.TH GGPLOT 1 2000-1月 "geom_color" "geom_color"
.SH NAME
geom_color \- Draw a ion m/z layer with a specific color channel
.SH SYNOPSIS
\fIgeom_color(\fBmz\fR as double, 
\fBcolor\fR as any, 
\fBtolerance\fR as any = "da:0.1", 
\fBpixel_render\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Draw a ion m/z layer with a specific color channel
.PP
.SH OPTIONS
.PP
\fBmz\fB \fR\- -. 
.PP
.PP
\fBcolor\fB \fR\- 
 this parameter usually be used for the r/g/b triple layer overlaps
. 
.PP
.PP
\fBtolerance\fB \fR\- -. 
.PP
.PP
\fBpixel_render\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
