.\" man page create by R# package system.
.TH GGPLOT 1 2000-Jan "geom_msimaging" "geom_msimaging"
.SH NAME
geom_msimaging \- 
.SH SYNOPSIS
\fIgeom_msimaging(\fBmz\fR as double, 
\fBtolerance\fR as any = "da:0.1", 
\fBpixel_render\fR as boolean = FALSE, 
\fBTrIQ\fR as double = 0.99, 
\fBcolor\fR as any = "viridis:turbo", 
\fBknnFill\fR as boolean = TRUE, 
\fBcolorLevels\fR as integer = 120, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBmz\fB \fR\- -. 
.PP
.PP
\fBtolerance\fB \fR\- 
 the mass tolerance error vaue for load intensity 
 data for each pixels from the raw data files.
. 
.PP
.PP
\fBpixel_render\fB \fR\- -. 
.PP
.PP
\fBTrIQ\fB \fR\- 
 the intensity cutoff threshold value for the target 
 ion layer use TrIQ algorithm.
. 
.PP
.PP
\fBcolor\fB \fR\- 
 the color set name
. 
.PP
.PP
\fBknnFill\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
