.\" man page create by R# package system.
.TH GGPLOT 1 2000-Jan "geom_MSIruler" "geom_MSIruler"
.SH NAME
geom_MSIruler \- Draw ruler overlaps of the ms-imaging
.SH SYNOPSIS
\fIgeom_MSIruler(\fBcolor\fR as any = "white", 
\fBwidth\fR as double = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
Draw ruler overlaps of the ms-imaging
.PP
.SH OPTIONS
.PP
\fBcolor\fB \fR\- -. 
.PP
.PP
\fBwidth\fB \fR\- 
 the ruler width on the imaging plot, unit of this parameter value is \fBum\fR.
. 
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
