.\" man page create by R# package system.
.TH GGPLOT 1 2000-01-01 "geom_color" "geom_color"
.SH NAME
geom_color \- 
.SH SYNOPSIS
\fIgeom_color(\fBmz\fR as double, 
\fBcolor\fR as any, 
\fBtolerance\fR as any = "da:0.1", 
\fBpixel_render\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
