.\" man page create by R# package system.
.TH GGPLOT 1 2000-01-01 "geom_msimaging" "geom_msimaging"
.SH NAME
geom_msimaging \- 
.SH SYNOPSIS
\fIgeom_msimaging(\fBmz\fR as double, 
\fBtolerance\fR as any = "da:0.1", 
\fBpixel_render\fR as boolean = FALSE, 
\fBTrIQ\fR as double = 0.5, 
\fBcolor\fR as any = "Jet", 
\fBknnFill\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
