.\" man page create by R# package system.
.TH GGPLOT 1 2000-01-01 "geom_MSIbackground" "geom_MSIbackground"
.SH NAME
geom_MSIbackground \- 
.SH SYNOPSIS
\fIgeom_MSIbackground(\fBbackground\fR as any);\fR
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
