.\" man page create by R# package system.
.TH GGPLOT 1 2000-Jan "geom_cmyk" "geom_cmyk"
.SH NAME
geom_cmyk \- 
.SH SYNOPSIS
\fIgeom_cmyk(\fBc\fR as any, 
\fBm\fR as any, 
\fBy\fR as any, 
\fBk\fR as any, 
\fBtolerance\fR as any = "da:0.1", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
