.\" man page create by R# package system.
.TH GGPLOT 1 2000-01-01 "geom_MSIbackground" "geom_MSIbackground"
.SH NAME
geom_MSIbackground \- config of the background of the MS-imaging charting plot.
.SH SYNOPSIS
\fIgeom_MSIbackground(\fBbackground\fR as any);\fR
.SH DESCRIPTION
.PP
config of the background of the MS-imaging charting plot.
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- 
 the background color value or character vector \fBTIC\fR or \fBBPC\fR.
. 
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
