.\" man page create by R# package system.
.TH GGPLOT 1 2000-01-01 "MSI_dimension" "MSI_dimension"
.SH NAME
MSI_dimension \- options for config the canvas dimension size of the ms-imaging raw data scans
.SH SYNOPSIS
\fIMSI_dimension(\fBdims\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
options for config the canvas dimension size of the ms-imaging raw data scans
.PP
.SH OPTIONS
.PP
\fBdims\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
