.\" man page create by R# package system.
.TH GGPLOT 1 2000-01-01 "MSI_knnfill" "MSI_knnfill"
.SH NAME
MSI_knnfill \- 
.SH SYNOPSIS
\fIMSI_knnfill(\fBk\fR as integer = 3, 
\fBqcut\fR as double = 0.8);\fR
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
