.\" man page create by R# package system.
.TH GGPLOT 1 2000-1月 "MSI_knnfill" "MSI_knnfill"
.SH NAME
MSI_knnfill \- configs the parameters for do Knn fill of the pixels
.SH SYNOPSIS
\fIMSI_knnfill(\fBk\fR as integer = 3, 
\fBqcut\fR as double = 0.85);\fR
.SH DESCRIPTION
.PP
configs the parameters for do Knn fill of the pixels
.PP
.SH OPTIONS
.PP
\fBk\fB \fR\- -. 
.PP
.PP
\fBqcut\fB \fR\- 
 the query block area percentage threshold value, 
 the higher cutoff of this parameter, the less fitting 
 will be perfermen on the pixels, the lower cutoff of 
 this parameter, the more interpolation will be.
. 
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
