.\" man page create by R# package system.
.TH GGPLOT 1 2000-Jan "MSI_gaussblur" "MSI_gaussblur"
.SH NAME
MSI_gaussblur \- options for gauss filter of the MS-imaging buffer
.SH SYNOPSIS
\fIMSI_gaussblur(\fBlevels\fR as integer = 30);\fR
.SH DESCRIPTION
.PP
options for gauss filter of the MS-imaging buffer
.PP
.SH OPTIONS
.PP
\fBlevels\fB \fR\- -. 
.PP
.SH DETAILS
.PP
the gauss blur function is not working well on the linux platform
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
