.\" man page create by R# package system.
.TH GGPLOT 1 2000-Jan "MSIheatmap" "MSIheatmap"
.SH NAME
MSIheatmap \- create R,G,B layers from the given dataframe columns data
.SH SYNOPSIS
\fIMSIheatmap(\fBR\fR as any, 
\fBG\fR as any = \fB<NULL>\fR, 
\fBB\fR as any = \fB<NULL>\fR, 
\fBmatrix\fR as <generic> dataframe = \fB<NULL>\fR, 
\fBdims\fR as any = "0,0", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create R,G,B layers from the given dataframe columns data
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- -. 
.PP
.PP
\fBR\fB \fR\- -. 
.PP
.PP
\fBG\fB \fR\- -. 
.PP
.PP
\fBB\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
this function generate the data source object for the ggplot
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
