.\" man page create by R# package system.
.TH GGPLOT 1 2000-01-01 "MSIheatmap" "MSIheatmap"
.SH NAME
MSIheatmap \- 
.SH SYNOPSIS
\fIMSIheatmap(\fBmatrix\fR as <generic> dataframe, 
\fBR\fR as string, 
\fBG\fR as string = \fB<NULL>\fR, 
\fBB\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
