.\" man page create by R# package system.
.TH GGPLOT 1 2000-Jan "pixelPack" "pixelPack"
.SH NAME
pixelPack \- create a pixel point pack object for create ggplot
.SH SYNOPSIS
\fIpixelPack(\fBpixels\fR as <generic> PixelData[]);\fR
.SH DESCRIPTION
.PP
create a pixel point pack object for create ggplot
.PP
.SH OPTIONS
.PP
\fBpixels\fB \fR\- 
 A pixel point vector for create a data pack
. 
.PP
.SH SEE ALSO
ggplot
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
