.\" man page create by R# package system.
.TH MSIFILTER 1 2000-Jan "knn_scale" "knn_scale"
.SH NAME
knn_scale \- Trying to fill the missing spatial spot on the imaging via knn method
.SH SYNOPSIS
\fIknn_scale(\fBk\fR as integer = 3, 
\fBq\fR as double = 0.65);\fR
.SH DESCRIPTION
.PP
Trying to fill the missing spatial spot on the imaging via knn method
.PP
.SH OPTIONS
.PP
\fBk\fB \fR\- -. 
.PP
.PP
\fBq\fB \fR\- -. 
.PP
.SH SEE ALSO
MSIfilter
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
