.\" man page create by R# package system.
.TH MSIFILTER 1 2000-Jan "log_scale" "log_scale"
.SH NAME
log_scale \- Normalized the raw input intensity value via log(N)
.SH SYNOPSIS
\fIlog_scale(\fBbase\fR as double = 2);\fR
.SH DESCRIPTION
.PP
Normalized the raw input intensity value via log(N)
.PP
.SH OPTIONS
.PP
\fBbase\fB \fR\- log(N), N=2 by default. 
.PP
.SH SEE ALSO
MSIfilter
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
