.\" man page create by R# package system.
.TH MSIFILTER 1 2000-Jan "soften_scale" "soften_scale"
.SH NAME
soften_scale \- Make convolution of the spatial data for make the imaging render result soften
.SH SYNOPSIS
\fIsoften_scale(\fBlayer\fR as <generic> SingleIonLayer = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
Make convolution of the spatial data for make the imaging render result soften
.PP
.SH SEE ALSO
MSIfilter
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
