.\" man page create by R# package system.
.TH MSIFILTER 1 2000-Jan "TrIQ_scale" "TrIQ_scale"
.SH NAME
TrIQ_scale \- Trim the raw input intensity value via the TrIQ algorithm
.SH SYNOPSIS
\fITrIQ_scale(\fBq\fR as double = 0.6);\fR
.SH DESCRIPTION
.PP
Trim the raw input intensity value via the TrIQ algorithm
.PP
.SH OPTIONS
.PP
\fBq\fB \fR\- -. 
.PP
.SH SEE ALSO
MSIfilter
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
