.\" man page create by R# package system.
.TH GGPLOT3 1 2000-Jan "view_camera" "view_camera"
.SH NAME
view_camera \- Create view camera for 3D plot
.SH SYNOPSIS
\fIview_camera(\fBview_distance\fR as integer = -75, 
\fBfov\fR as integer = 100000, 
\fBangle\fR as any = [31.5,65,125]);\fR
.SH DESCRIPTION
.PP
Create view camera for 3D plot
.PP
.SH OPTIONS
.PP
\fBangle\fB \fR\- 
 should be a numeric vector with 3 elements, the camera view angle to the canvas
. 
.PP
.SH SEE ALSO
ggplot3
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
