.\" man page create by R# package system.
.TH GGPLOT2 1 2000-01-01 "geom_jitter" "geom_jitter"
.SH NAME
geom_jitter \- 
.SH SYNOPSIS
\fIgeom_jitter(\fBmapping\fR as <generic> ggplotReader = \fB<NULL>\fR, 
\fBdata\fR as any = \fB<NULL>\fR, 
\fBstat\fR as any = "identity", 
\fBwidth\fR as double = 0.5, 
\fBradius\fR as double = 10, 
\fBalpha\fR as double = 0.85, 
\fBcolor\fR as list = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
