.\" man page create by R# package system.
.TH GGPLOT2 1 2000-1月 "geom_vline" "geom_vline"
.SH NAME
geom_vline \- Reference lines: horizontal, vertical, and diagonal
.SH SYNOPSIS
\fIgeom_vline(\fBxintercept\fR as double, 
\fBcolor\fR as any = "black", 
\fBline_width\fR as double = 2, 
\fBlinetype\fR as <integer> DashStyle = [Solid]);\fR
.SH DESCRIPTION
.PP
Reference lines: horizontal, vertical, and diagonal
 
 These geoms add reference lines (sometimes called rules) to a plot, 
 either horizontal, vertical, or diagonal (specified by slope and
 intercept). These are useful for annotating plots.
.PP
.SH OPTIONS
.PP
\fBxintercept\fB \fR\- 
 Parameters that control the position of the line. If these are set, 
 data, mapping and show.legend are overridden.
. 
.PP
.PP
\fBcolor\fB \fR\- -. 
.PP
.PP
\fBline_width!\fB \fR\- -. 
.PP
.PP
\fBlinetype\fB \fR\- -. 
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
