.\" man page create by R# package system.
.TH GGPLOT2 1 2000-1月 "geom_path" "geom_path"
.SH NAME
geom_path \- Connect observations
.SH SYNOPSIS
\fIgeom_path();\fR
.SH DESCRIPTION
.PP
Connect observations
 
 geom_path() connects the observations in the order in which they 
 appear in the data. geom_line() connects them in order of the 
 variable on the x axis. geom_step() creates a stairstep plot, highlighting 
 exactly when changes occur. The group aesthetic determines which 
 cases are connected together.
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
