.\" man page create by R# package system.
.TH GGPLOT2 1 2000-01-01 "geom_histogram" "geom_histogram"
.SH NAME
geom_histogram \- Histograms and frequency polygons
.SH SYNOPSIS
\fIgeom_histogram(\fBbins\fR as integer, 
\fBcolor\fR as any = \fB<NULL>\fR, 
\fBalpha\fR as double = 1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Histograms and frequency polygons
 
 Visualise the distribution of a single continuous variable by dividing 
 the x axis into bins and counting the number of observations in each bin. 
 Histograms (geom_histogram()) display the counts with bars;
.PP
.SH OPTIONS
.PP
\fBbins\fB \fR\- 
 Number of bins. Overridden by binwidth. Defaults to 30.
. 
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
