.\" man page create by R# package system.
.TH GGPLOT2 1 2000-1月 "geom_convexHull" "geom_convexHull"
.SH NAME
geom_convexHull \- 
.SH SYNOPSIS
\fIgeom_convexHull(\fBmapping\fR as <generic> ggplotReader = \fB<NULL>\fR, 
\fBalpha\fR as double = 1);\fR
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
