.\" man page create by R# package system.
.TH GGPLOT2 1 2000-Jan "geom_signif" "geom_signif"
.SH NAME
geom_signif \- Create significance layer
.SH SYNOPSIS
\fIgeom_signif(\fBcomparisons\fR as list, 
\fBtest\fR as string = "t.test");\fR
.SH DESCRIPTION
.PP
Create significance layer
.PP
.SH OPTIONS
.PP
\fBcomparisons\fB \fR\- 
 the comparision groups tuple list, each tuple value should be 
 two group label for extract the corresponding sample vector 
 from the ggplot input raw dataframe for run the \fBt.test\fR.
. 
.PP
.PP
\fBtest\fB \fR\- 
 the stats test method between two groups: t.test or wilcox.test
. 
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
