.\" man page create by R# package system.
.TH GGPLOT2 1 2000-Jan "geom_hline" "geom_hline"
.SH NAME
geom_hline \- 
.SH SYNOPSIS
\fIgeom_hline(\fByintercept\fR as double, 
\fBcolor\fR as any = "black", 
\fBline_width\fR as double = 3, 
\fBlinetype\fR as <integer> DashStyle = [Solid]);\fR
.SH OPTIONS
.PP
\fByintercept\fB \fR\- -. 
.PP
.PP
\fBcolor\fB \fR\- -. 
.PP
.PP
\fBline_width!\fB \fR\- -. 
.PP
.PP
\fBlinetype\fB \fR\- -. 
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
