.\" man page create by R# package system.
.TH GGPLOT2 1 2000-Jan "ggsave" "ggsave"
.SH NAME
ggsave \- 
.SH SYNOPSIS
\fIggsave(\fBfilename\fR as string, 
\fBplot\fR as any = "~last_plot()", 
\fBdevice\fR as any = \fB<NULL>\fR, 
\fBpath\fR as any = \fB<NULL>\fR, 
\fBscale\fR as double = 1, 
\fBwidth\fR as <generic> Int32 = \fB<NULL>\fR, 
\fBheight\fR as <generic> Int32 = \fB<NULL>\fR, 
\fBunits\fR as <integer> CssUnit = [Pixels], 
\fBdpi\fR as integer = 300, 
\fBlimitsize\fR as boolean = TRUE, 
\fBbg\fR as any = \fB<NULL>\fR, 
..., 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBfilename\fB \fR\- -. 
.PP
.PP
\fBplot\fB \fR\- -. 
.PP
.PP
\fBdevice\fB \fR\- -. 
.PP
.PP
\fBpath\fB \fR\- -. 
.PP
.PP
\fBscale\fB \fR\- -. 
.PP
.PP
\fBwidth\fB \fR\- -. 
.PP
.PP
\fBheight\fB \fR\- -. 
.PP
.PP
\fBunits\fB \fR\- -. 
.PP
.PP
\fBdpi\fB \fR\- -. 
.PP
.PP
\fBlimitsize\fB \fR\- -. 
.PP
.PP
\fBbg\fB \fR\- -. 
.PP
.PP
\fBargs\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
