.\" man page create by R# package system.
.TH GGPLOT2 1 2000-Jan "last_plot" "last_plot"
.SH NAME
last_plot \- Retrieve the last plot to be modified or created.
.SH SYNOPSIS
\fIlast_plot();\fR
.SH DESCRIPTION
.PP
Retrieve the last plot to be modified or created.
 
 Retrieve the last plot to be modified or created.
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
