.\" man page create by R# package system.
.TH GGPLOT2 1 2000-1月 "scale_y_continuous" "scale_y_continuous"
.SH NAME
scale_y_continuous \- Position scales for continuous data (x & y)
.SH SYNOPSIS
\fIscale_y_continuous(\fBlabels\fR as string = \fB<NULL>\fR, 
\fBlimits\fR as double = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Position scales for continuous data (x & y)
.PP
.SH OPTIONS
.PP
\fBlabels\fB \fR\- 
 One of:
 
 + \fBNULL\fR for no labels
 + waiver() for the default labels computed by the transformation object
 + A character vector giving labels (must be same length As breaks)
 + A Function that() takes the breaks As input And returns labels As output. Also accepts rlang lambda Function notation.
. 
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
