.\" man page create by R# package system.
.TH GGPLOT2 1 2000-1月 "stat_compare_means" "stat_compare_means"
.SH NAME
stat_compare_means \- 
.SH SYNOPSIS
\fIstat_compare_means(\fBmethod\fR as string = "anova", 
\fBref_group\fR as string = ".all.", 
\fBhide_ns\fR as boolean = TRUE);\fR
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
