.\" man page create by R# package system.
.TH GGPLOT2 1 2000-Jan "stat_compare_means" "stat_compare_means"
.SH NAME
stat_compare_means \- default create anova test for compares all groups
.SH SYNOPSIS
\fIstat_compare_means(\fBmethod\fR as string = "anova", 
\fBref_group\fR as string = ".all.", 
\fBhide_ns\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
default create anova test for compares all groups
.PP
.SH OPTIONS
.PP
\fBmethod\fB \fR\- -. 
.PP
.PP
\fBref_group\fB \fR\- -. 
.PP
.PP
\fBhide_ns\fB \fR\- hide not sig result?. 
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
