.\" man page create by R# package system.
.TH GGPLOT2 1 2000-1月 "stat_pvalue_manual" "stat_pvalue_manual"
.SH NAME
stat_pvalue_manual \- 
.SH SYNOPSIS
\fIstat_pvalue_manual(\fBcomparisons\fR as <generic> dataframe);\fR
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
