.\" man page create by R# package system.
.TH GGPLOT2 1 2000-Jan "theme_minimal" "theme_minimal"
.SH NAME
theme_minimal \- 
.SH SYNOPSIS
\fItheme_minimal();\fR
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
