.\" man page create by R# package system.
.TH GGPLOT2 1 2000-01-01 "xlab" "xlab"
.SH NAME
xlab \- Modify axis, legend, and plot labels
.SH SYNOPSIS
\fIxlab(\fBlabel\fR as string);\fR
.SH DESCRIPTION
.PP
Modify axis, legend, and plot labels
 
 Good labels are critical for making your plots accessible to a 
 wider audience. Always ensure the axis and legend labels display 
 the full variable name. Use the plot title and subtitle to 
 explain the main findings. It's common to use the caption to 
 provide information about the data source. tag can be used for 
 adding identification tags to differentiate between multiple 
 plots.
.PP
.SH OPTIONS
.PP
\fBlabel\fB \fR\- 
 The title of the respective axis (for xlab() or ylab()) or 
 of the plot (for ggtitle()).
. 
.PP
.SH DETAILS
.PP
You can also set axis and legend labels in the individual scales 
 (using the first argument, the name). If you're changing other 
 scale options, this is recommended.
 
 If a plot already has a title, subtitle, caption, etc., And you want 
 To remove it, you can Do so by setting the respective argument To 
 NULL. For example, If plot p has a subtitle, Then p + labs(subtitle = NULL) 
 will remove the subtitle from the plot.
.PP
.SH SEE ALSO
ggplot2
.SH FILES
.PP
ggplot.dll
.PP
.SH COPYRIGHT
Copyright xieguigang<xie.guigang@gcmodeller.org> 2021, all rights reserved.
