.\" man page create by R# package system.
.TH GGSPATIAL 1 2000-Jan "format_ruler" "format_ruler"
.SH NAME
format_ruler \- test for the ruler formatter
.SH SYNOPSIS
\fIformat_ruler(\fBx\fR as any);\fR
.SH DESCRIPTION
.PP
test for the ruler formatter
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- should be a numeric vector of \fBμm\fR for auto formatted. 
.PP
.SH SEE ALSO
ggspatial
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
