.\" man page create by R# package system.
.TH GGSPATIAL 1 2000-Jan "geom_spatialtile" "geom_spatialtile"
.SH NAME
geom_spatialtile \- add a spatial overlaps of the STdata on current SMdata imaging
.SH SYNOPSIS
\fIgeom_spatialtile(\fBtile\fR as <generic> SpatialMapping, 
\fBgeneID\fR as string, 
\fBSTdata\fR as any, 
\fBcolorSet\fR as any = "viridis:turbo", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
add a spatial overlaps of the STdata on current SMdata imaging
.PP
.SH OPTIONS
.PP
\fBtile\fB \fR\- -. 
.PP
.SH SEE ALSO
ggspatial
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
