.\" man page create by R# package system.
.TH GGSPATIAL 1 2000-Jan "geom_spatialtile" "geom_spatialtile"
.SH NAME
geom_spatialtile \- add a spatial overlaps of the STdata on current SMdata imaging
.SH SYNOPSIS
\fIgeom_spatialtile(\fBtile\fR as <generic> SpatialMapping, 
\fBgeneID\fR as string = \fB<NULL>\fR, 
\fBSTdata\fR as any = \fB<NULL>\fR, 
\fBcolorSet\fR as any = "grays", 
\fBsize\fR as double = 13, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
add a spatial overlaps of the STdata on current SMdata imaging
.PP
.SH OPTIONS
.PP
\fBtile\fB \fR\- A collection of the spatial spot mapping. 
.PP
.PP
\fBSTdata\fB \fR\- the spatial transcriptomics data matrix. 
.PP
.PP
\fBgeneID\fB \fR\- 
 the gene ID for pull the spatial expression from the **`STdata`**. 
. 
.PP
.PP
\fBcolorSet\fB \fR\- 
 the color set data for rendering the gene expression spatial heatmap
. 
.PP
.PP
\fBsize\fB \fR\- the spot size when drawing the spatial expression. 
.PP
.SH SEE ALSO
ggspatial
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
