.\" man page create by R# package system.
.TH GGSPATIAL 1 2000-Jan "geom_spatialScatter" "geom_spatialScatter"
.SH NAME
geom_spatialScatter \- draw scatter layer with a given x and y coordinates.
.SH SYNOPSIS
\fIgeom_spatialScatter(\fBx\fR as any, 
\fBy\fR as any, 
\fBcolors\fR as any, 
\fBsize\fR as double = 3, 
\fBalpha\fR as double = 0.8, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
draw scatter layer with a given x and y coordinates.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a numeric vector of pixel x. 
.PP
.PP
\fBy\fB \fR\- a numeric vector of pixel y. 
.PP
.PP
\fBcolors\fB \fR\- the colors for rendering each scatter spot. 
.PP
.PP
\fBsize\fB \fR\- the spot size for the drawing. 
.PP
.PP
\fBalpha\fB \fR\- the transparency alpha value for drawing the scatter points.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
ggspatial
.SH FILES
.PP
MSImaging.dll
.PP
.SH COPYRIGHT
Copyright (c) 2021 この中二病に爆焔を！
