#' Count the number of MS1 scans as imaging pixels
#'
#' This function calculates the total number of MS1 scans in an mzpack object,
#' which corresponds to the pixel dimensions in MS imaging spatial data.
#' Each MS1 scan represents a spatial coordinate (pixel) in the 2D imaging plane.
#'
#' @param raw An mzpack object containing mass spectrometry data. The object must
#' include MS1-level scan data in its MS property. Typically generated by
#' mzR or other MS data parsers that support imaging data structure.
#'
#' @return An integer value representing the total number of pixels in the
#' associated MS imaging experiment. This is equivalent to the number of MS1
#' scans stored in the MS property of the input object.
#'
#' @details
#' The function accesses the MS property of the mzpack object, which stores
#' a list of MS scans, and returns the count of MS1-level scans. In MS imaging,
#' each MS1 scan is spatially mapped to a specific (x,y) coordinate, forming
#' the basis for intensity-based image reconstruction.
#'
#' @examples
#' \dontrun{
#' # Assuming 'mzpack_data' is a valid mzpack object
#' pixel_count <- npixels(mzpack_data)
#' cat("Total imaging pixels:", pixel_count)
#' }
#'
const npixels = function(raw) {
	length([raw]::MS);
}